### ISSUE TITLE
Use JMH @Setup and @TearDown

### ISSUE THREAD

**Issue by andreaTP** [vy/fiber-test#6]
RATIONALE:
in these benchmarks the performance of the "Ring Benchmark" is measured all together with the time needed to "prepare" and "shutdown" the environment.

This happen to perform a quite unfair comparison.
e.g.  having a simple `Thread.join` is of course faster than an `ActorSystem.shutdown` since the latter will ensure you have a coordinated shutdown of a possible connected cluster.

Since JMH is already in use you can leverage the built-in functions:
http://tutorials.jenkov.com/java-performance/jmh.html#state-setup-and-teardown

to setup and shut down the environment, having eventually separated benchmarks for measuring these particular stages.

**Comment by vy** [comment]
Hey @andreaTP! Thanks for taking time to check the sources. Indeed, scheduler start-up and tear-down latencies are included in the benchmarks. Actually, to exclude their overhead from the benchmarks, I run two separate test sets: `messagePassingCount=1` and `messagePassingCount=10e6`. Here, the former delivers the aforementioned start-up and tear-down overheads. Though as you noticed we might have used the `@State` to pre-allocate them. The reason I did not go that route in the initial design is that the definition of cachable schedulers/fibers/threads/actors <del>is</del> was not aligned between different implementations. That being said, I see your point and it should be doable. I will see what I can do. In the meantime, PRs are welcome.

**Comment by vy** [comment]
Finally, after quite some struggle, done.
